export const GET_EMPLOYEE_REQUEST = 'GET_EMPLOYEE_REQUEST';
export const GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS';
export const GET_EMPLOYEE_FAILURE = 'GET_EMPLOYEE_FAILURE';

export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';
 
export const GET_EMPLOYEE_DETAILS_REQUEST = 'GET_EMPLOYEE_DETAILS_REQUEST';
export const GET_EMPLOYEE_DETAILS_SUCCESS = 'GET_EMPLOYEE_DETAILS_SUCCESS';
export const GET_EMPLOYEE_DETAILS_FAILURE = 'GET_EMPLOYEE_DETAILS_FAILURE';
 
export const UPDATE_EMPLOYEE_DETAILS_REQUEST = 'UPDATE_EMPLOYEE_DETAILS_REQUEST';
export const UPDATE_EMPLOYEE_DETAILS_SUCCESS = 'UPDATE_EMPLOYEE_DETAILS_SUCCESS';
export const UPDATE_EMPLOYEE_DETAILS_FAILURE = 'UPDATE_EMPLOYEE_DETAILS_FAILURE';

export const UPDATE_EMPLOYEE_NAME = 'UPDATE_EMPLOYEE_NAME';

export const ADD_EMPLOYEE_DETAILS_REQUEST = 'ADD_EMPLOYEE_DETAILS_REQUEST';
export const ADD_EMPLOYEE_DETAILS_SUCCESS = 'ADD_EMPLOYEE_DETAILS_SUCCESS';
export const ADD_EMPLOYEE_DETAILS_FAILURE = 'ADD_EMPLOYEE_DETAILS_FAILURE';

